### ISSUE TITLE
incorrect ff0/ff1 operation 

### ISSUE THREAD

**Issue by LingHua209134** [T-head-Semi/thead-extension-spec#5]
The _Operation_ of ff0/ff1 is not correspond to _Description_. In ff0 process, it is supposed to check from 63 bit to 0 bit, and return from 0 to 63.

**Comment by Cooper-Qu** [comment]
Fixed.
https://github.com/T-head-Semi/thead-extension-spec/commit/5d4ed751a2bc39541a37fb12ccdb3cd13b054ca2
