### ISSUE TITLE
Is XTheadVector equal to RVV 0.7.1 ?

### ISSUE THREAD

**Issue by Du-Chao** [T-head-Semi/thead-extension-spec#51]
Could we use the "-march=rv64gc_xtheadvector" GCC parameter for a XuanTie C920 (V1) core ?
Thanks.

**Comment by cmuellner** [comment]
XTheadVector is not equal to RVV 0.7.1.
But XTheadVector is very similar to RVV 0.7.1.

Details can be found here: https://github.com/T-head-Semi/thead-extension-spec/blob/master/xtheadvector.adoc

**Comment by Du-Chao** [comment]
> XTheadVector is not equal to RVV 0.7.1. But XTheadVector is very similar to RVV 0.7.1.
> 
> Details can be found here: https://github.com/T-head-Semi/thead-extension-spec/blob/master/xtheadvector.adoc

Thanks.
So could I use the option '-march=rv64gc_xtheadvector' to build a binary for XuanTie C920 ?

**Comment by cmuellner** [comment]
> > XTheadVector is not equal to RVV 0.7.1. But XTheadVector is very similar to RVV 0.7.1.
> > Details can be found here: https://github.com/T-head-Semi/thead-extension-spec/blob/master/xtheadvector.adoc
> 
> Thanks. So could I use the option '-march=rv64gc_xtheadvector' to build a binary for XuanTie C920 ?

Yes, but to make this work, you will need a kernel supporting XTheadVector as well.

**Comment by Du-Chao** [comment]
Thanks.
