### ISSUE TITLE
`XTheadMemIdx`: contradicting mnemonics

### ISSUE THREAD

**Issue by a4lg** [T-head-Semi/thead-extension-spec#6]
It seems instruction table and per-instruction description has different mnemonics.

For instance, from the instruction table,

> | RV32 | RV64 | Mnemonic | Instruction |
> |:---- |:---- |:-------- |:-----------|
> |`Y` | `Y` | th.lrb *rd, rs1, rs2, imm2* | Load indexed byte |

But in section 9.1.23. th.lrb:

> **Mnemonic**
> th.lrb *rd, (rs1), rs2, imm2*

(both are quotes from version 2022-11-07 2.1.0)

Currently, GNU Binutils implements the former (without paren).  But...
*   At least, we should fix the manual for consistency (even if "no paren form" is correct) and
*   If the latter mnemonic is the correct format (like other `XTheadMemIdx` instructions like `th.lbia`), GNU Binutils should be fixed (I can handle that).

**Comment by Cooper-Qu** [comment]
Sorry for late reply.

The correct format is "th.lrb rd, (rs1), rs2, imm2"
I will fix the document, and I would really appreciate it if you could fix it in GNU Binutils

**Comment by Cooper-Qu** [comment]
Sorry, after I reconfirmed, the correct format should be "th.lrb rd, rs1, rs2, imm2".

And I have fixed the mnemonic description.(https://github.com/T-head-Semi/thead-extension-spec/commit/c295bde469853139d9dd2f936c079a5aab9c4859)
