### ISSUE TITLE
`XTheadFMemIdx`: No parens?

### ISSUE THREAD

**Issue by a4lg** [T-head-Semi/thead-extension-spec#7]
As I pointed out in #6, there are some inconsistencies in `XTheadMemIdx`.

`XTheadFMemIdx` does not have such inconsistencies **in the manual** but replacing `rs1` with `(rs1)` may be an option to keep consistency with other RISC-V instructions.

Is not having parens around `rs1` is intentional?  If not, we should fix both the manual and GNU Binutils (I can handle the GNU Binutils part).

**Comment by Cooper-Qu** [comment]
As I mentioned in the https://github.com/T-head-Semi/thead-extension-spec/issues/6

I will fix the document. And if you can fix in the GNU Binutils, I will would really appreciate it.
